import { tablesNames } from "@/constants";
import type { CrudOperation } from "@/types/api";
import {
  BANNERS,
  BANNERS_CREATE,
  BANNERS_DELETE,
  BANNERS_DETAILS,
  BANNERS_UPDATE,
  BATCHES,
  BATCHES_CREATE,
  BATCHES_DELETE,
  BATCHES_DETAILS,
  BATCHES_UPDATE,
  CATEGORIES,
  CATEGORIES_CREATE,
  CATEGORIES_DELETE,
  CATEGORIES_DETAILS,
  CATEGORIES_UPDATE,
  CITIES,
  CITIES_CREATE,
  CITIES_DELETE,
  CITIES_DETAILS,
  CITIES_UPDATE,
  CLASSES,
  CLASSES_BELONG_USERS,
  CLASSES_CREATE,
  CLASSES_DELETE,
  CLASSES_DETAILS,
  CLASSES_UPDATE,
  COUNTRIES,
  COUNTRIES_CREATE,
  COUNTRIES_DELETE,
  COUNTRIES_DETAILS,
  COUNTRIES_UPDATE,
  DISTRICTS,
  DISTRICTS_CREATE,
  DISTRICTS_DELETE,
  DISTRICTS_DETAILS,
  DISTRICTS_UPDATE,
  DOWNLOAD_EXCEL,
  EXPORT_EXCEL,
  FAQS,
  FAQS_CREATE,
  FAQS_DELETE,
  FAQS_DETAILS,
  FAQS_UPDATE,
  FORMS,
  FORMS_CREATE_COMPREHENSIVE,
  FORMS_DELETE,
  FORMS_DETAILS,
  FORMS_UPDATE_COMPREHENSIVE,
  GENERAL_SETTINGS,
  GENERAL_SETTINGS_CREATE,
  GENERAL_SETTINGS_DELETE,
  GENERAL_SETTINGS_DETAILS,
  GENERAL_SETTINGS_UPDATE,
  IMPORT_EXCEL,
  INSTRUCTORS,
  INSTRUCTORS_CREATE,
  INSTRUCTORS_DELETE,
  INSTRUCTORS_DETAILS,
  INSTRUCTORS_UPDATE,
  MATERIAL_CONTENTS,
  MATERIAL_CONTENTS_CREATE,
  MATERIAL_CONTENTS_DELETE,
  MATERIAL_CONTENTS_DETAILS,
  MATERIAL_CONTENTS_UPDATE,
  MATERIAL_DETAILS,
  MATERIAL_DETAILS_CREATE,
  MATERIAL_DETAILS_DELETE,
  MATERIAL_DETAILS_DETAILS,
  MATERIAL_DETAILS_UPDATE,
  MATERIAL_SESSIONS,
  MATERIAL_SESSIONS_CREATE,
  MATERIAL_SESSIONS_DELETE,
  MATERIAL_SESSIONS_DETAILS,
  MATERIAL_SESSIONS_UPDATE,
  MATERIALS,
  MATERIALS_CREATE,
  MATERIALS_DELETE,
  MATERIALS_DETAILS,
  MATERIALS_UPDATE,
  NOTIFICATIONS,
  NOTIFICATIONS_CREATE,
  NOTIFICATIONS_DELETE,
  NOTIFICATIONS_DETAILS,
  NOTIFICATIONS_UPDATE,
  PERMISSIONS,
  PERMISSIONS_CREATE,
  PERMISSIONS_DELETE,
  PERMISSIONS_DETAILS,
  PERMISSIONS_UPDATE,
  PROFILE,
  PROFILE_UPDATE,
  QUIZZES,
  QUIZZES_CREATE_COMPREHENSIVE,
  QUIZZES_DELETE,
  QUIZZES_DETAILS,
  QUIZZES_UPDATE,
  ROLES,
  ROLES_CREATE,
  ROLES_DELETE,
  ROLES_DETAILS,
  ROLES_UPDATE,
  STAGES,
  STAGES_CREATE,
  STAGES_DELETE,
  STAGES_DETAILS,
  STAGES_UPDATE,
  STUDENTS,
  STUDENTS_CREATE,
  STUDENTS_DELETE,
  STUDENTS_DETAILS,
  STUDENTS_UPDATE,
  SUPERVISORS,
  SUPERVISORS_CREATE,
  SUPERVISORS_DELETE,
  SUPERVISORS_DETAILS,
  SUPERVISORS_UPDATE,
  USER_CLASSES,
  USER_CLASSES_CREATE,
  USER_CLASSES_DELETE,
  USER_CLASSES_DETAILS,
  USER_CLASSES_UPDATE,
  USER_QUIZ_RESULTS,
  USER_QUIZ_RESULTS_CREATE,
  USER_QUIZ_RESULTS_DELETE,
  USER_QUIZ_RESULTS_DETAILS,
  USER_QUIZ_RESULTS_UPDATE,
  USERS,
  USERS_CREATE,
  USERS_DELETE,
  USERS_DETAILS,
  USERS_UPDATE,
} from "./queries";

export const TABLE_QUERY_MAP: Partial<
  Record<
    (typeof tablesNames)[keyof typeof tablesNames],
    Partial<Record<CrudOperation, string>>
  >
> = {
  [tablesNames.users]: {
    get: USERS,
    create: USERS_CREATE,
    update: USERS_UPDATE,
    delete: USERS_DELETE,
    details: USERS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.students]: {
    get: STUDENTS,
    create: STUDENTS_CREATE,
    update: STUDENTS_UPDATE,
    delete: STUDENTS_DELETE,
    details: STUDENTS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.instructors]: {
    get: INSTRUCTORS,
    create: INSTRUCTORS_CREATE,
    update: INSTRUCTORS_UPDATE,
    delete: INSTRUCTORS_DELETE,
    details: INSTRUCTORS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.supervisors]: {
    get: SUPERVISORS,
    create: SUPERVISORS_CREATE,
    update: SUPERVISORS_UPDATE,
    delete: SUPERVISORS_DELETE,
    details: SUPERVISORS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.profile]: {
    get: PROFILE,
    create: PROFILE_UPDATE,
    update: PROFILE_UPDATE,
    delete: PROFILE_UPDATE,
    details: PROFILE,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.countries]: {
    get: COUNTRIES,
    create: COUNTRIES_CREATE,
    update: COUNTRIES_UPDATE,
    delete: COUNTRIES_DELETE,
    details: COUNTRIES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.cities]: {
    get: CITIES,
    create: CITIES_CREATE,
    update: CITIES_UPDATE,
    delete: CITIES_DELETE,
    details: CITIES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.districts]: {
    get: DISTRICTS,
    create: DISTRICTS_CREATE,
    update: DISTRICTS_UPDATE,
    delete: DISTRICTS_DELETE,
    details: DISTRICTS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.roles]: {
    get: ROLES,
    create: ROLES_CREATE,
    update: ROLES_UPDATE,
    delete: ROLES_DELETE,
    details: ROLES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.permissions]: {
    get: PERMISSIONS,
    create: PERMISSIONS_CREATE,
    update: PERMISSIONS_UPDATE,
    delete: PERMISSIONS_DELETE,
    details: PERMISSIONS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.general_settings]: {
    get: GENERAL_SETTINGS,
    create: GENERAL_SETTINGS_CREATE,
    update: GENERAL_SETTINGS_UPDATE,
    delete: GENERAL_SETTINGS_DELETE,
    details: GENERAL_SETTINGS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.categories]: {
    get: CATEGORIES,
    create: CATEGORIES_CREATE,
    update: CATEGORIES_UPDATE,
    delete: CATEGORIES_DELETE,
    details: CATEGORIES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.stages]: {
    get: STAGES,
    create: STAGES_CREATE,
    update: STAGES_UPDATE,
    delete: STAGES_DELETE,
    details: STAGES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.batches]: {
    get: BATCHES,
    create: BATCHES_CREATE,
    update: BATCHES_UPDATE,
    delete: BATCHES_DELETE,
    details: BATCHES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.classes]: {
    get: CLASSES,
    create: CLASSES_CREATE,
    update: CLASSES_UPDATE,
    delete: CLASSES_DELETE,
    details: CLASSES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.belongUsersClasses]: {
    get: CLASSES_BELONG_USERS,
    create: CLASSES_BELONG_USERS,
    update: CLASSES_BELONG_USERS,
    delete: CLASSES_BELONG_USERS,
    details: CLASSES_BELONG_USERS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.userClasses]: {
    get: USER_CLASSES,
    create: USER_CLASSES_CREATE,
    update: USER_CLASSES_UPDATE,
    delete: USER_CLASSES_DELETE,
    details: USER_CLASSES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.materials]: {
    get: MATERIALS,
    create: MATERIALS_CREATE,
    update: MATERIALS_UPDATE,
    delete: MATERIALS_DELETE,
    details: MATERIALS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.materialDetails]: {
    get: MATERIAL_DETAILS,
    create: MATERIAL_DETAILS_CREATE,
    update: MATERIAL_DETAILS_UPDATE,
    delete: MATERIAL_DETAILS_DELETE,
    details: MATERIAL_DETAILS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.materialSessions]: {
    get: MATERIAL_SESSIONS,
    create: MATERIAL_SESSIONS_CREATE,
    update: MATERIAL_SESSIONS_UPDATE,
    delete: MATERIAL_SESSIONS_DELETE,
    details: MATERIAL_SESSIONS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.materialContents]: {
    get: MATERIAL_CONTENTS,
    create: MATERIAL_CONTENTS_CREATE,
    update: MATERIAL_CONTENTS_UPDATE,
    delete: MATERIAL_CONTENTS_DELETE,
    details: MATERIAL_CONTENTS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.forms]: {
    get: FORMS,
    create: FORMS_CREATE_COMPREHENSIVE,
    update: FORMS_UPDATE_COMPREHENSIVE,
    delete: FORMS_DELETE,
    details: FORMS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.quizzes]: {
    get: QUIZZES,
    create: QUIZZES_CREATE_COMPREHENSIVE,
    update: QUIZZES_UPDATE,
    delete: QUIZZES_DELETE,
    details: QUIZZES_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.banners]: {
    get: BANNERS,
    create: BANNERS_CREATE,
    update: BANNERS_UPDATE,
    delete: BANNERS_DELETE,
    details: BANNERS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.userQuizResults]: {
    get: USER_QUIZ_RESULTS,
    create: USER_QUIZ_RESULTS_CREATE,
    update: USER_QUIZ_RESULTS_UPDATE,
    delete: USER_QUIZ_RESULTS_DELETE,
    details: USER_QUIZ_RESULTS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.faqs]: {
    get: FAQS,
    create: FAQS_CREATE,
    update: FAQS_UPDATE,
    delete: FAQS_DELETE,
    details: FAQS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
  [tablesNames.notifications]: {
    get: NOTIFICATIONS,
    create: NOTIFICATIONS_CREATE,
    update: NOTIFICATIONS_UPDATE,
    delete: NOTIFICATIONS_DELETE,
    details: NOTIFICATIONS_DETAILS,
    download: DOWNLOAD_EXCEL,
    import: IMPORT_EXCEL,
    export: EXPORT_EXCEL,
  },
};
