import type { Metadata } from "next";
import { Cairo, DM_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import { AppProviders } from "@/components/providers";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";
import { routing } from "@/i18n/routing";
import { getDirection } from "@/lib/direction";
import { type Locale, hasLocale } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const [session, messages] = await Promise.all([auth(), getMessages()]);

  return (
    <html
      lang={locale}
      dir={getDirection(locale)}
      className={`${plusJakartaSans.variable} ${dmMono.variable} ${cairo.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <AppProviders
          session={session}
          locale={locale as Locale}
          messages={messages}
        >
          <Toaster />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
